### PR TITLE
Issues with drone distance chechs in >0.18.43

### PR DESCRIPTION
**Pull request by oiltanker**
There are issues with drone distance evaluations. Use as reference.

**Discussion thread [Bots unable to repair](https://mods.factorio.com/mod/Construction_Drones/discussion/5f2c4d9d3f87ac176455fba5)**

### CODE REVIEW

**Comment by paul** [comment]
This fixed it for me, as well. @oiltanker how did you come up with those values?

**Comment by paul** [comment]
Actually, there's still a couple things not working. The seem to not be able to reliably place assemblers, and are unable to mine the large rocks (the ones with both stone and coal).

**Comment by oiltanker** [comment]
Ah yes, i didn't test all the things, because it was late at night. But the values were taken through testing the distances while debugging.

The thing is that the `in_construction_range` value was got when radius of the target was to small, and some constant was taken.

I guess i can try and comment out this constant and see the difference for myself.

**Comment by oiltanker** [comment]
Alternative idea is to check whether there is a way to tell if drone completed movement order successfully , and won't move any closer without checking the distance.

If it is possible, then we won't need to do random based value guessing.

**Comment by oiltanker** [comment]
I just looked through change log fir 0.18.43 and there is this thing: *Fixed that biters could attack entities beyond their attack range.* Seems to be the culprit, as other things seem unrelated.

**Comment by oiltanker** [comment]
I think I know what the issue is. As mentioned in my previous comment, there was some pathing or range changes.

Through testing i figured out that disabling the `oofah` minimum radius leads, in now current version of **0.18.44**, to about *1/2* offset in all distances to target for drones, and that fixes a lot of things, BUT there is another issue.

This *1/2* offset is relevant not for target, but for closest blocking entity, so as the result, drones can't fix turrets behind walls, as difference in distance nears *1*.

Possible solutions:
- increase construction range, by increasing drone interact distance.
- Agree that turrets behind two layers of wall are to be inaccessible (looks silly tbh, as they just won't come an inch towards the target), but that would leave distance check running each tick, possibly causing performance drops, so some repair feasibility checks would be appropriate.
- Don't do anything :P

**Comment by longneck** [comment]
#18

**Comment by oiltanker** [comment]
I think I have a working workaround, so when there is successful completion of drone's path, I write position to drone_data, and then next time the bot is out of range i check whether drone position is different at least by *0.01*. Works like a charm, for me.

Btw, are drones supposed to do this:
drone attacking the tree
It seems to be attacking the tree, because it is in it's way, like a biter would do.

**Comment by oiltanker** [comment]
I force pushed alternative fix, as it is more universal imho.

**Pull request closed without merging**
